kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: global-rolebinding
  namespace: default
  labels:
    app: demo-microservice
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
  namespace: default
roleRef:
  kind: Role
  name: api-role
  apiGroup: ""