kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-role
  namespace: default
  labels:
    app: demo-microservice
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["demo-microservice", "demo-microservice-dev", "mock-microservice", "mock-microservice-dev"]
  verbs: ["update", "delete", "get"]